### ISSUE TITLE
Is there any benefits to implement the "ticker" channel?

### ISSUE THREAD

**Issue by xiaoyual666** [fabianboesiger/ftx#93]
Hi Admin, 

This is just a newbie question, not an issue actually..
I noticed that you have already provided the convenience methods like best_bid and best_ask from Orderbook. Why should we still need a "ticker" channel?

**Comment by MaxFangX** [comment]
Good question! I'm not sure. Maybe the `Ticker` channel has better latency since it only streams the best bid and ask rather than updates to every part of the order book. This library is pretty easily extensible to new endpoints and channels, so whenever some additional functionality becomes useful to someone, generally they will go ahead and implement it. Since no one has implemented the `Ticker` channel yet I would assume that no one has found the slightly reduced bandwidth useful enough to be worth the effort. There's no rush (or need) to implement every endpoint anyway, only what people find useful.

**Comment by fabianboesiger** [comment]
Agreed, if you are just interested in best bids and asks, use the Ticker channel as it will most likely have better latency. Most of the time however, it makes more sense to keep track of the whole orderbook when executing market orders as best bid/ask volumes may be very small.

**Comment by xiaoyual666** [comment]
Thanks @MaxFangX  and @fabianboesiger! Your comments helped a lot!
